//이 라우터는 몽고 로컬 데이터베이스 사용 시, 사전에 비디오 데이터를 셋팅하기 위한 라우터입니다.

var express = require('express');
var router = express.Router();
var model = require('../models');
var Videos = model.Videos;

router.get('/set_videos', function(req,res){
    var video_array=[{"title":"강아지","content":"강아지 나오는 동영상","cast":"하리","feature":"귀여움","genre":"동물","type":"original","episode":[{"time":"0.5","epi_content":"하리가 새 장난감을 선물받았다."}],"category":"movie"},
    {"title":"고양이","content":"귀여운 고양이들이 나옵니다.","cast":"삼색고양이, 아기고양이","feature":"귀여움","genre":"동물","type":"original","episode":[{"time":"0.3","epi_content":"삼색고양이가 츄르를 먹고있다."},{"time":"0.1","epi_content":"아기고양이가 밥을 먹고 있다."}],"category":"TV"},    {"title":"cut","content":"일본 사람들이 토론을 하고 있다.","cast":"일본사람들","feature":"토론","genre":"토론","type":"original","episode":[{"time":"2","epi_content":"열띤 토론을 하고 있는 일본 사람들"}],"category":"TV"},
    {"title":"연모","src":"https://www.youtube.com/embed/cV4R4pwfxX4?controls=0&autoplay=1","content":"죽은 오빠 대신 남장을 하고 왕세자로 살아가는 쌍둥이 여동생. 궁녀에게 철벽을 치며 문무에 전념하려는 중인데, 이를 어째. 세자 교육을 맡은 남자에게 자꾸 눈길이 가. 이거 혹시, 사랑?","cast":"박은빈, 로운, 남윤수","feature":"로맨스","genre":"TV 드라마.로맨스, 한국 드라마, 만화책 원작 TV프로그램","ost":[{"song":"그림자 사랑","singer":"SUPER JUNIOR-K.R.Y.","ost_src":"https://www.youtube.com/embed/v0AOm0SadbU?controls=0"},{"song":"알아요","singer":"린","ost_src":"https://www.youtube.com/embed/DIghhFgapzw?controls=0"}],"episode":[{"time":69,"epi_content":"빈궁이 쌍생아를 출산한 날, 왕궁에 피바람이 몰아친다. 그로부터 몇 년 후, 자신과 똑같이 생긴 궁녀를 발견한 왕세자 이휘. 어머니에게 이 사실을 말해 충격을 가져온다.","epi_src":"https://www.youtube.com/embed/SxHXk6gP7RE"},{"time":70,"epi_content":"비극적 사건의 전모를 알게 된 담이. 오빠를 대신해 남장을 하고 왕세자로 살아간다. 한편, 명나라 유학을 마치고 의원이 된 지운은 발진 환자를 위해 약재를 구하러 떠난다.","epi_src":"https://www.youtube.com/embed/SxHXk6gP7RE"},{"time":70,"epi_content":"휘가 지운의 목숨을 살리고 사라진다. 다시는 마주칠 일이 없다고 생각하며. 그러나 야밤에 궁궐에서 지운을 보고 소스라치게 놀라는 휘. 저자가 어떻게 궁궐에?","epi_src":"https://www.youtube.com/embed/xKS_BgzPFOI"},{"time":70,"epi_content":"지운이 만만한 상대가 아님을 간파한 휘. 자신의 스승이 된 지운을 사임시키기 위해 사력을 다한다. 한편, 휘는 이현과 함께 궐 밖으로 잠행을 나간다.","epi_src":"https://www.youtube.com/embed/SxHXk6gP7RE"},{"time":64,"epi_content":"궐에 사는 이들을 잘 보살피라는 지운의 충고. 보란 듯이 시찰에 나선 휘 덕분에 궐에는 때아닌 소동이 일어난다. 창운군은 묘한 향으로 휘를 시험하기 위해 계략을 꾸민다.","epi_src":"https://www.youtube.com/embed/SxHXk6gP7RE"},{"time":64,"epi_content":"저하께서 왜 이 서책을? 휘의 책상에서 익숙한 서책을 발견한 지운은 혼란스럽다. 한편 소중한 이들을 살리기 위해 위험을 무릅쓰는 지운. 마지막으로 휘에게 도움을 청한다.","epi_src":"https://www.youtube.com/embed/SxHXk6gP7RE"}],"type":"youtube","category":"TV"},
    {"title":"지옥","src":"https://www.youtube.com/embed/ga3pXJEngms?controls=0&autoplay=1","content":"어느 날 기이한 존재로부터 지옥행을 선고받은 사람들. 충격과 두려움에 휩싸인 도시에 대혼란의 시대가 도래한다. 신의 심판을 외치며 세를 확장하려는 종교단체와 진실을 파헤치는 자들의 이야기.","cast":"유아인, 김현주, 박정민","feature":"폭력적인, 어두운, 긴장감 넘치는","genre":"TV 프로그램·미스터리, TV 프로그램·범죄, 웹툰 원작 한국 드라마","ost":[{"song":"인트로(Intro)","singer":"Unknown","ost_src":"https://www.youtube.com/embed/8gTTmo-9Qbw?controls=0"},{"song":"엔딩테마","singer":"Unknown","ost_src":"https://www.youtube.com/embed/GNBkuCCp2w4?controls=0"}],"episode":[{"time":48,"epi_content":"대낮에 도시 한복판에서 한 남자를 무자비하게 죽이는 괴생물체들. 새진리회 의장 정진수는 공포에 질린 시민들에게 설파한다. 죄지은 자들에게 지옥행이 선고된 것이라고.","epi_src":"https://www.youtube.com/embed/huTOivFBXFY"},{"time":53,"epi_content":"또 다른 지옥행이 예고되었다. 5일 후 죽는다는 신의 고지를 받고 정진수를 찾아간 박정자. 새진리회는 거액을 제안한다. 그 대가는? 지옥 시연을 생방송으로 중계하는 것.","epi_src":"https://www.youtube.com/embed/JbRiuqg6Sy4"},{"time":53,"epi_content":"인간은 더욱 정의로워질 수 있습니다. 방송에서 신의 심판이 도래했음을 경고하는 정진수. 진경훈 형사가 가출한 딸을 찾는 동안 화살촉은 민혜진 변호사에게 응징을 가한다.","epi_src":"https://www.youtube.com/embed/JbRiuqg6Sy4"},{"time":42,"epi_content":"무언가를 숨긴 채 사라진 동료를 찾아 나선 배영재 피디. 외진 낚시터에서 끔찍한 광경을 목격하고 아연실색한다. 한편, 전혀 예상치 못한 장소에서 천사의 예언이 전달된다.","epi_src":"https://www.youtube.com/embed/JbRiuqg6Sy4"},{"time":55,"epi_content":"반드시 답을 찾아야 한다. 절망에 빠진 배영재는 간절한 마음으로 한 남자를 추적한다. 증발한 자들의 행적을 쫓던 새진리회. 소문으로 떠돌던 수상한 단체의 꼬리를 잡는다.","epi_src":"https://www.youtube.com/embed/JbRiuqg6Sy4"},{"time":60,"epi_content":"세상에 알려지면 대혼란이 일어날 것이다. 다음 시연 당사자의 놀라운 정체를 알게 된 새진리회는 필사의 추적을 시작한다. 무슨 일이 있어도 시연의 공개를 막아야 한다.","epi_src":"https://www.youtube.com/embed/JbRiuqg6Sy4"}],"type":"youtube","category":"TV"},
    {"title":"정직한 후보","src":"https://www.youtube.com/embed/x5fe4Xf6ENs?controls=0&autoplay=1","content":"거짓말이 제일 쉬운 3선 국회의원 ‘주상숙’에게 청천벽력이 떨어진다.하루아침에 거짓말은 1도 할 수 없는 ‘진실의 주둥이’를 갖게 된 것!최고의 무기인 ‘거짓말’을 잃자그녀의 인생은 송두리째 흔들리게 되는데…","cast":"라미란, 김무열, 나문희","feature":"코미디, 익살스러운, 허당매력","genre":"코미디 영화, 영화","episode":[{"time":104,"epi_content":"거짓말을 일삼는 3선 국회의원 주상숙이 선거를 앞둔 어느 날 하루 아침에 거짓말을 못하게 되면서 벌어지는 이야기","epi_src":"https://www.youtube.com/embed/x5fe4Xf6ENs"}],"type":"youtube","category":"movie"},
    {"title":"윤희에게","src":"https://www.youtube.com/embed/dOeHK4p5Ypw?controls=0&autoplay=1","content":"평범한 일상을 살아가던 '윤희' 앞으로 도착한 한 통의 편지.편지를 몰래 읽어본 딸 '새봄'은 편지의 내용을 숨긴 채발신인이 살고 있는 곳으로 여행을 제안하고,'윤희'는 비밀스러웠던 첫사랑의 기억으로 가슴이 뛴다.'새봄'과 함께 여행을 떠난 ‘윤희’는끝없이 눈이 내리는 그곳에서첫사랑을 만날지도 모른다는 기대를 품는데…","cast":"김희애, 김소혜, 나카무라 유코","feature":"드라마, 로맨스, 첫사랑","genre":"영화, 드라마/로맨스","episode":[{"time":105,"epi_content":"하얀 입김이 올라오는 날 도착한 편지 한 통. 딸 새봄과 평범한 나날을 보내던 윤희의 가슴이 두근거린다. 편지의 발신인을 찾아 낯선 곳으로 여행을 떠난 새봄과 윤희. 새하얀 눈이 가득 쌓인 이곳에서 다시... 만날 수 있을까?","epi_src":"https://www.youtube.com/embed/dOeHK4p5Ypw"}],"type":"youtube","category":"movie"},
    {"title":"마이네임","src":"https://www.youtube.com/embed/TOTswK8Km74?controls=0&autoplay=1","content":"아빠를 잃었다. 그것도 바로 눈앞에서.남은 딸은 결심한다. 반드시 내 손으로 복수하겠노라고. 목표를 위해서라면 방법은 상관없다. 마약 조직의 언더커버가 되어 경찰에 잠입하는 것이라 해도.","cast":"한소희, 박희순, 남보현","feature":"어두운, 긴장감 넘치는","genre":"TV 프로그램·범죄, 한국 드라마, 프로그램·스릴러","ost":[{"song":"My Name","singer":"황상준","ost_src":"https://www.youtube.com/embed/_Cu-5NzGfQA?controls=0"},{"song":"mediocre life","singer":"황상준","ost_src":"https://www.youtube.com/embed/5ufW2cCHCEg?controls=0"},{"song":"alone","singer":"박은지","ost_src":"https://www.youtube.com/embed/RFivIL43Hb0?controls=0"}],"episode":[{"time":54,"epi_content":"최악의 생일이었다. 생일을 축하해주러 찾아온 아빠의 죽음을 눈앞에서 목격한 윤지우. 복수에 혈안이 된 그녀는 무모한 행동도 서슴지 않는다. 범인을 찾을 가능성만 있다면.","epi_src":"https://www.youtube.com/embed/q7i7XY3VE20"},{"time":46,"epi_content":"최무진은 도강재에게 엄중한 벌을 내린다. 그러고는 지우를 밖으로 불러낸 무진의 한 마디. 오늘 윤지우는 죽었다! 몇 년 후, 지우는 새로운 신분으로 경찰에 잠입한다.","epi_src":"https://www.youtube.com/embed/-NsNHD0LXV4"},{"time":47,"epi_content":"타깃을 체포하러 출동하는 마수대. 지우는 뜻밖의 상황에 당황하지만, 이내 서둘러 행동에 나선다. 한편 악의에 찬 보스가 이끄는 신흥 마약 조직이 무진의 제국을 위협한다.","epi_src":"https://www.youtube.com/embed/-NsNHD0LXV4"},{"time":46,"epi_content":"강재가 무진에게 전쟁을 선포했다. 이 상황을 기회로 활용하려는 차기호. 지우에게서 수상한 낌새를 눈치챈 기호의 지시에, 전필도는 은밀하게 지우의 뒤를 밟기 시작한다.","epi_src":"https://www.youtube.com/embed/-NsNHD0LXV4"},{"time":50,"epi_content":"죽음의 위기에서 가까스로 탈출한 지우와 필도. 이 사건을 계기로 경찰의 칼끝은 강재를 향한다. 얼마 후, 사무실에서 낯익은 얼굴과 마주친 지우는 불안감을 감추지 못한다.","epi_src":"https://www.youtube.com/embed/-NsNHD0LXV4"},{"time":49,"epi_content":"집으로 배달된 사진 한 장. 그 사진 속에서 발견한 의외의 인물. 지우는 이제 무엇을 믿어야 할지 혼란스럽기만 하다. 무진은 뜻한 바를 이룰 수 있는 다른 방법을 선택한다.","epi_src":"https://www.youtube.com/embed/-NsNHD0LXV4"}],"type":"youtube","category":"TV"},
    {"title":"슬기로운 의사생활","src":"https://www.youtube.com/embed/35Dmi5XYcng?controls=0&autoplay=1","content":"탄생과 죽음이 공존하는, 인생의 축소판이라고 불리는 병원에서 특별한 하루하루를 살아가는 사람들의 이야기를 그린 드라마","cast":"조정석, 유연석, 정경호","feature":"메디컬 TV 시리즈, 한국 드라마, TV 드라마","genre":"힐링, 진심 어린","ost":[{"song":"바람이 부네요","singer":"이소라","ost_src":"https://www.youtube.com/embed/YB4IV27-i6k?controls=0"},{"song":"너에게 난, 나에게 넌","singer":"미도와 파라솔","ost_src":"https://www.youtube.com/embed/tLGHKyZs0Gk?controls=0"},{"song":"사랑하게 될 줄 알았어","singer":"전미도","ost_src":"https://www.youtube.com/embed/rOCymN-Rwiw?controls=0"}],"episode":[{"time":82,"epi_content":"99학번 의예과 동갑내기 친구들, 이젠 내 환자 보기에도 24시간이 부족한 40대 의사가 되었다. 각자 방식으로 살아가던 다섯 명의 친구들에게 한 통의 전화가 걸려오는데!","epi_src":"https://www.youtube.com/embed/BgbJXbw5V7o"},{"time":82,"epi_content":"20년 만에 한 병원에서 만나게 된 친구들. 오늘도 각자 한 사람의 의사로서 최선을 다한다. 한편, 송화는 환자 차트에서 왜인지 낯설지 않은 이름을 발견하는데...","epi_src":"https://www.youtube.com/embed/0eHU3MUk6rc"},{"time":88,"epi_content":"환자에게 다정한 듯 엄격한, 때론 무심하지만 배려 넘치는 교수 5인방. 실습생들 눈엔 슈퍼히어로가 따로 없다. 한편, 익준에겐 반가운 사람이 찾아오는데...","epi_src":"https://www.youtube.com/embed/ojkadJ0g3Cc"},{"time":79,"epi_content":"뚱~한 표정을 하고 겨우 몇 마디 하는 석형 때문에 민하는 오늘도 답답하기만 하고. 홍도와 윤복은 병원 밖에서 송화의 비밀스러운 취미 생활을 알게 되는데...","epi_src":"https://www.youtube.com/embed/hu1dUmaB1ik"},{"time":72,"epi_content":"겨울은 유독 본인에게만 차가운 정원에게 칭찬 한마디를 기대해보지만, 쉽지 않다. 흉부외과에는 새로운 교수가 부임해오고... 오늘도 재학의 24시간은 모자라다.","epi_src":"https://www.youtube.com/embed/IyxpeEgV2sY"},{"time":81,"epi_content":"대시에 어떤 대답도 없는 익순 때문에 종일 휴대폰만 들여다보는 준완. 한편, 정원이 오래 지켜봐 온 환자 상태가 악화되고, 보호자에게 어려운 소식을 전하는데.","epi_src":"https://www.youtube.com/embed/JbRiuqg6Sy4"}],"type":"youtube","category":"TV"}
    ];
    Videos.insertMany(video_array,(err,docs)=>{
        if(err) throw err;
        res.send('비디오 셋팅 완료');
    })
});


module.exports = router;